language: ruby
sudo: required
rvm:
- 2.2.1
test:
  adapter: postgresql
  database: testapp_test
  username: postgres
env:
  global:
    secure: kLRUVn1B4OKHmEwU9zYFVSK/5deFYoi+3WTUoIJO73UqXWQuQF8OICBfGbviDZtIXUbnjGwQtBccszg5ZOf2sT7T0TdvF4Z/hKiHkEE+x2NZhC3GwZZBpmn+yuHsj2c2O09hUpqq6mxllRrhuu8pyZ653iwuhcrx4fVbXKlCCQgU5lG4tuEhCiTJVEEjjw5MUWL3Y3Ri2ZjNKS1yY0p5xoQSVEsHLVSrTS/Vl1JtvA7noIdI5B4RtTFcJn46Oiw0msucN6qfNSn0Bvt5Jx5ixLobx/4QCJOmcG1jj9W5ShaQo573ji6gb4rkkPTcA5Bkd9X4WhVahNzqzUuowMnWO6bYWB8yVZxbuJC6jOy0PGkivAhj76MdmW9J07nQEx1NpWU3HeJ/AD+y5RWReCFZG100Ju2epArjuPvm0FfFb/IC46P+QUy6mt+ouswGPooh1fQR1vI4VHuqSB0yccGhZkNMiD/XT+NRvWF6N3cSxkhF5kcFn8vYuHmKM/gYIUGgBwTilkl9XifXhV185V/7cyigy0lWqRBN60w8zL7pMs2jzlNhyzkngJriNmp/SX/FJqcsH17UKajbvefYGuBQc7yi6f7aZlyjHfhG5Hdj9DWdQ0+TrBJv4wlEmSg0tZG+nmnmqAMfi1qZAYQ/OHEOfsB/CJJKg/lNSckgxnAJXAE=
addons:
  apt:
    sources:
    - heroku
    packages:
    - heroku-toolbelt
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
before_script:
  - psql -c 'create database testapp_test;' -U postgres
  - "./selenium/setup_selenium_tests.sh"
  - echo -e "Host heroku.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - git remote add heroku git@heroku.com:rocky-scrubland-staging.git
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Clear your current Heroku SSH keys:
  - heroku keys:clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
script:
  - "./runtests.sh"
