# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f534401bafed3b14a2fa9a0ead5c6e31a237673c86c369dbc5de976c089b2346787e73aded136dc0019521dff53ebb9864b87e2c36280a846d31e4aa5859a3af

test:
  secret_key_base: 68e2167893248cd68e0eb7cfad8549f0e9d159196b18fea749ae69adb26bbdac2f4ac00e64b4a9bbed5093b70c965b14bce3f8502382abe52ab42510c7bab98d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
